name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v2
        with:
          github_user_name: joaotiodoro
          outputs: |
            dist/github-contribution-grid-snake.svg
